export const userInfo = [
    {
        name: 'Joe Philips',
        age: 23,
        favoriteColor: 'blue',
        favoriteAnimal: 'cat',
    },
    {
        name: 'Alice Johnson',
        age: 30,
        favoriteColor: 'green',
        favoriteAnimal: 'dog',
    },
    {
        name: 'Bob Smith',
        age: 25,
        favoriteColor: 'red',
        favoriteAnimal: 'bird',
    },
    {
        name: 'Michael Scott',
        age: 45,
        favoriteColor: 'blue',
        favoriteAnimal: 'dog',
    },
    {
        name: 'Pam Beesly',
        age: 34,
        favoriteColor: 'pink',
        favoriteAnimal: 'cat',
    },
    {
        name: 'Jim Halpert',
        age: 36,
        favoriteColor: 'green',
        favoriteAnimal: 'fish',
    },
    {
        name: 'Dwight Schrute',
        age: 40,
        favoriteColor: 'yellow',
        favoriteAnimal: 'beetle',
    },
    {
        name: 'Stanley Hudson',
        age: 60,
        favoriteColor: 'red',
        favoriteAnimal: 'turtle',
    },
    {
        name: 'Angela Martin',
        age: 38,
        favoriteColor: 'white',
        favoriteAnimal: 'cat',
    },
    {
        name: 'Kevin Malone',
        age: 42,
        favoriteColor: 'brown',
        favoriteAnimal: 'dog',
    },
    {
        name: 'Oscar Martinez',
        age: 39,
        favoriteColor: 'purple',
        favoriteAnimal: 'parrot',
    },
    {
        name: 'Toby Flenderson',
        age: 50,
        favoriteColor: 'grey',
        favoriteAnimal: 'hamster',
    },
    {
        name: 'Ryan Howard',
        age: 30,
        favoriteColor: 'orange',
        favoriteAnimal: 'rabbit',
    },
    {
        name: 'Phyllis Vance',
        age: 55,
        favoriteColor: 'magenta',
        favoriteAnimal: 'guinea pig',
    },
    {
        name: 'Meredith Palmer',
        age: 48,
        favoriteColor: 'cyan',
        favoriteAnimal: 'ferret',
    },
    {
        name: 'Creed Bratton',
        age: 70,
        favoriteColor: 'black',
        favoriteAnimal: 'snake',
    },
    {
        name: 'Kelly Kapoor',
        age: 29,
        favoriteColor: 'violet',
        favoriteAnimal: 'lizard',
    },
    {
        name: 'Darryl Philbin',
        age: 44,
        favoriteColor: 'teal',
        favoriteAnimal: 'bird',
    },
    {
        name: 'Andy Bernard',
        age: 36,
        favoriteColor: 'gold',
        favoriteAnimal: 'turtle',
    },
    {
        name: 'Phyllis Vance',
        age: 55,
        favoriteColor: 'magenta',
        favoriteAnimal: 'guinea pig',
    },
    {
        name: 'Stanley Hudson',
        age: 60,
        favoriteColor: 'red',
        favoriteAnimal: 'turtle',
    },
    {
        name: 'Angela Martin',
        age: 38,
        favoriteColor: 'white',
        favoriteAnimal: 'cat',
    },
    {
        name: 'Kevin Malone',
        age: 42,
        favoriteColor: 'brown',
        favoriteAnimal: 'dog',
    },
    {
        name: 'Oscar Martinez',
        age: 39,
        favoriteColor: 'purple',
        favoriteAnimal: 'parrot',
    },
    {
        name: 'Toby Flenderson',
        age: 50,
        favoriteColor: 'grey',
        favoriteAnimal: 'hamster',
    },
]